# Information about the device
deviceInfo:
    host: 192.168.255.142
    user: root
    passwd: alpine
    port: 22
    rootFolder: /

# Information regarding mail transmission
emailCredentials:
    user: malus.sec@gmail.com
    passwd: Malus123/
    recipient: costin.carabas@gmail.com

# The folders where the data is extracted
outputFolders:
    extractFsFolder: iPod5_iOS812_12B440
    dynamicOutputFolder: iPod5_iOS812_12B440_dynamic

scripts:
    startDynamicAnalysis: ../automatedDataExtraction/dynamicAnalysisPrototype/startDynamicAnalysis.sh
    stopDynamicAnalysis: ../automatedDataExtraction/dynamicAnalysisPrototype/stopDynamicAnalysis.sh
    staticAnalysis: ../automatedDataExtraction/dataExtractorForConnectedDevice.sh
